language: android
android:
  components:
    - platform-tools
    - tools
    - extra
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-18

